spring:
  datasource:
    #    url: ${DATABASE_URL}
    #    username: ${DATABASE_USERNAME}
    #    password: ${DATABASE_PASSWORD}
    url: jdbc:mysql://localhost:3306/fitnessdb
    username: fitness
    password: fitness

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sql:
    init:
      mode: always
      platform: mysql
      # data-locations: classpath:data-mysql.sql

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 8640000000 # 100 day
      refresh-token:
        expiration: 604800000 # 7 days
