spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitnessdb
    username: fitness
    password: fitness
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: aydindiefitness@gmail.com
    password: nbwj bjzf cwlq xgky
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 8640000000 # 100 day
      refresh-token:
        expiration: 604800000 # 7 days
