spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitnessdb
    username: fitness
    password: fitness
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 864000000 # 10 day
      refresh-token:
        expiration: 604800000 # 7 days
